################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Each subdirectory must supply rules for building sources it contributes
src/core/HardwareSerial.o: C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/cores/tivac/HardwareSerial.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: GNU Compiler'
	"C:/Users/14169/AppData/Local/Energia15/packages/energia/tools/arm-none-eabi-gcc/8.3.1-20190703/bin/arm-none-eabi-gcc-8.3.1.exe" -c -mcpu=cortex-m4 -march=armv7e-m -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -Dprintf=iprintf -DF_CPU=120000000L -DENERGIA_EK_TM4C1294XL -DENERGIA_ARCH_TIVAC -DENERGIA=23 -DARDUINO=10610 -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system/driverlib" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system/inc" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/cores/tivac" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/variants/EK-TM4C1294XL" -I"C:/Users/14169/workspace_v10/tivac_EK-TM4C1294XL_core" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/tools/arm-none-eabi-gcc/8.3.1-20190703/arm-none-eabi/include" -Os -ffunction-sections -fdata-sections -g -gdwarf-3 -gstrict-dwarf -w -Wall --param max-inline-insns-single=500 -mabi=aapcs -MMD -MP -MF"src/core/$(basename $(<F)).d_raw" -MT"$(@)" -std=gnu++11 -fno-rtti -fno-threadsafe-statics -fno-exceptions $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/IPAddress.o: C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/cores/tivac/IPAddress.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: GNU Compiler'
	"C:/Users/14169/AppData/Local/Energia15/packages/energia/tools/arm-none-eabi-gcc/8.3.1-20190703/bin/arm-none-eabi-gcc-8.3.1.exe" -c -mcpu=cortex-m4 -march=armv7e-m -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -Dprintf=iprintf -DF_CPU=120000000L -DENERGIA_EK_TM4C1294XL -DENERGIA_ARCH_TIVAC -DENERGIA=23 -DARDUINO=10610 -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system/driverlib" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system/inc" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/cores/tivac" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/variants/EK-TM4C1294XL" -I"C:/Users/14169/workspace_v10/tivac_EK-TM4C1294XL_core" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/tools/arm-none-eabi-gcc/8.3.1-20190703/arm-none-eabi/include" -Os -ffunction-sections -fdata-sections -g -gdwarf-3 -gstrict-dwarf -w -Wall --param max-inline-insns-single=500 -mabi=aapcs -MMD -MP -MF"src/core/$(basename $(<F)).d_raw" -MT"$(@)" -std=gnu++11 -fno-rtti -fno-threadsafe-statics -fno-exceptions $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/MACAddress.o: C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/cores/tivac/MACAddress.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: GNU Compiler'
	"C:/Users/14169/AppData/Local/Energia15/packages/energia/tools/arm-none-eabi-gcc/8.3.1-20190703/bin/arm-none-eabi-gcc-8.3.1.exe" -c -mcpu=cortex-m4 -march=armv7e-m -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -Dprintf=iprintf -DF_CPU=120000000L -DENERGIA_EK_TM4C1294XL -DENERGIA_ARCH_TIVAC -DENERGIA=23 -DARDUINO=10610 -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system/driverlib" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system/inc" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/cores/tivac" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/variants/EK-TM4C1294XL" -I"C:/Users/14169/workspace_v10/tivac_EK-TM4C1294XL_core" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/tools/arm-none-eabi-gcc/8.3.1-20190703/arm-none-eabi/include" -Os -ffunction-sections -fdata-sections -g -gdwarf-3 -gstrict-dwarf -w -Wall --param max-inline-insns-single=500 -mabi=aapcs -MMD -MP -MF"src/core/$(basename $(<F)).d_raw" -MT"$(@)" -std=gnu++11 -fno-rtti -fno-threadsafe-statics -fno-exceptions $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/Print.o: C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/cores/tivac/Print.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: GNU Compiler'
	"C:/Users/14169/AppData/Local/Energia15/packages/energia/tools/arm-none-eabi-gcc/8.3.1-20190703/bin/arm-none-eabi-gcc-8.3.1.exe" -c -mcpu=cortex-m4 -march=armv7e-m -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -Dprintf=iprintf -DF_CPU=120000000L -DENERGIA_EK_TM4C1294XL -DENERGIA_ARCH_TIVAC -DENERGIA=23 -DARDUINO=10610 -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system/driverlib" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system/inc" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/cores/tivac" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/variants/EK-TM4C1294XL" -I"C:/Users/14169/workspace_v10/tivac_EK-TM4C1294XL_core" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/tools/arm-none-eabi-gcc/8.3.1-20190703/arm-none-eabi/include" -Os -ffunction-sections -fdata-sections -g -gdwarf-3 -gstrict-dwarf -w -Wall --param max-inline-insns-single=500 -mabi=aapcs -MMD -MP -MF"src/core/$(basename $(<F)).d_raw" -MT"$(@)" -std=gnu++11 -fno-rtti -fno-threadsafe-statics -fno-exceptions $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/Stream.o: C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/cores/tivac/Stream.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: GNU Compiler'
	"C:/Users/14169/AppData/Local/Energia15/packages/energia/tools/arm-none-eabi-gcc/8.3.1-20190703/bin/arm-none-eabi-gcc-8.3.1.exe" -c -mcpu=cortex-m4 -march=armv7e-m -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -Dprintf=iprintf -DF_CPU=120000000L -DENERGIA_EK_TM4C1294XL -DENERGIA_ARCH_TIVAC -DENERGIA=23 -DARDUINO=10610 -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system/driverlib" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system/inc" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/cores/tivac" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/variants/EK-TM4C1294XL" -I"C:/Users/14169/workspace_v10/tivac_EK-TM4C1294XL_core" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/tools/arm-none-eabi-gcc/8.3.1-20190703/arm-none-eabi/include" -Os -ffunction-sections -fdata-sections -g -gdwarf-3 -gstrict-dwarf -w -Wall --param max-inline-insns-single=500 -mabi=aapcs -MMD -MP -MF"src/core/$(basename $(<F)).d_raw" -MT"$(@)" -std=gnu++11 -fno-rtti -fno-threadsafe-statics -fno-exceptions $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/Tone.o: C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/cores/tivac/Tone.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: GNU Compiler'
	"C:/Users/14169/AppData/Local/Energia15/packages/energia/tools/arm-none-eabi-gcc/8.3.1-20190703/bin/arm-none-eabi-gcc-8.3.1.exe" -c -mcpu=cortex-m4 -march=armv7e-m -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -Dprintf=iprintf -DF_CPU=120000000L -DENERGIA_EK_TM4C1294XL -DENERGIA_ARCH_TIVAC -DENERGIA=23 -DARDUINO=10610 -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system/driverlib" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system/inc" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/cores/tivac" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/variants/EK-TM4C1294XL" -I"C:/Users/14169/workspace_v10/tivac_EK-TM4C1294XL_core" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/tools/arm-none-eabi-gcc/8.3.1-20190703/arm-none-eabi/include" -Os -ffunction-sections -fdata-sections -g -gdwarf-3 -gstrict-dwarf -w -Wall --param max-inline-insns-single=500 -mabi=aapcs -MMD -MP -MF"src/core/$(basename $(<F)).d_raw" -MT"$(@)" -std=gnu++11 -fno-rtti -fno-threadsafe-statics -fno-exceptions $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/WInterrupts.o: C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/cores/tivac/WInterrupts.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: GNU Compiler'
	"C:/Users/14169/AppData/Local/Energia15/packages/energia/tools/arm-none-eabi-gcc/8.3.1-20190703/bin/arm-none-eabi-gcc-8.3.1.exe" -c -mcpu=cortex-m4 -march=armv7e-m -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -Dprintf=iprintf -DF_CPU=120000000L -DENERGIA_EK_TM4C1294XL -DENERGIA_ARCH_TIVAC -DENERGIA=23 -DARDUINO=10610 -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system/driverlib" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system/inc" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/cores/tivac" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/variants/EK-TM4C1294XL" -I"C:/Users/14169/workspace_v10/tivac_EK-TM4C1294XL_core" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/tools/arm-none-eabi-gcc/8.3.1-20190703/arm-none-eabi/include" -Os -ffunction-sections -fdata-sections -g -gdwarf-3 -gstrict-dwarf -w -Wall --param max-inline-insns-single=500 -mabi=aapcs -MMD -MP -MF"src/core/$(basename $(<F)).d_raw" -MT"$(@)" -std=gnu11 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/WMath.o: C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/cores/tivac/WMath.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: GNU Compiler'
	"C:/Users/14169/AppData/Local/Energia15/packages/energia/tools/arm-none-eabi-gcc/8.3.1-20190703/bin/arm-none-eabi-gcc-8.3.1.exe" -c -mcpu=cortex-m4 -march=armv7e-m -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -Dprintf=iprintf -DF_CPU=120000000L -DENERGIA_EK_TM4C1294XL -DENERGIA_ARCH_TIVAC -DENERGIA=23 -DARDUINO=10610 -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system/driverlib" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system/inc" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/cores/tivac" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/variants/EK-TM4C1294XL" -I"C:/Users/14169/workspace_v10/tivac_EK-TM4C1294XL_core" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/tools/arm-none-eabi-gcc/8.3.1-20190703/arm-none-eabi/include" -Os -ffunction-sections -fdata-sections -g -gdwarf-3 -gstrict-dwarf -w -Wall --param max-inline-insns-single=500 -mabi=aapcs -MMD -MP -MF"src/core/$(basename $(<F)).d_raw" -MT"$(@)" -std=gnu++11 -fno-rtti -fno-threadsafe-statics -fno-exceptions $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/WString.o: C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/cores/tivac/WString.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: GNU Compiler'
	"C:/Users/14169/AppData/Local/Energia15/packages/energia/tools/arm-none-eabi-gcc/8.3.1-20190703/bin/arm-none-eabi-gcc-8.3.1.exe" -c -mcpu=cortex-m4 -march=armv7e-m -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -Dprintf=iprintf -DF_CPU=120000000L -DENERGIA_EK_TM4C1294XL -DENERGIA_ARCH_TIVAC -DENERGIA=23 -DARDUINO=10610 -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system/driverlib" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system/inc" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/cores/tivac" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/variants/EK-TM4C1294XL" -I"C:/Users/14169/workspace_v10/tivac_EK-TM4C1294XL_core" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/tools/arm-none-eabi-gcc/8.3.1-20190703/arm-none-eabi/include" -Os -ffunction-sections -fdata-sections -g -gdwarf-3 -gstrict-dwarf -w -Wall --param max-inline-insns-single=500 -mabi=aapcs -MMD -MP -MF"src/core/$(basename $(<F)).d_raw" -MT"$(@)" -std=gnu++11 -fno-rtti -fno-threadsafe-statics -fno-exceptions $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/itoa.o: C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/cores/tivac/itoa.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: GNU Compiler'
	"C:/Users/14169/AppData/Local/Energia15/packages/energia/tools/arm-none-eabi-gcc/8.3.1-20190703/bin/arm-none-eabi-gcc-8.3.1.exe" -c -mcpu=cortex-m4 -march=armv7e-m -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -Dprintf=iprintf -DF_CPU=120000000L -DENERGIA_EK_TM4C1294XL -DENERGIA_ARCH_TIVAC -DENERGIA=23 -DARDUINO=10610 -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system/driverlib" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system/inc" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/cores/tivac" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/variants/EK-TM4C1294XL" -I"C:/Users/14169/workspace_v10/tivac_EK-TM4C1294XL_core" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/tools/arm-none-eabi-gcc/8.3.1-20190703/arm-none-eabi/include" -Os -ffunction-sections -fdata-sections -g -gdwarf-3 -gstrict-dwarf -w -Wall --param max-inline-insns-single=500 -mabi=aapcs -MMD -MP -MF"src/core/$(basename $(<F)).d_raw" -MT"$(@)" -std=gnu11 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/main.o: C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/cores/tivac/main.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: GNU Compiler'
	"C:/Users/14169/AppData/Local/Energia15/packages/energia/tools/arm-none-eabi-gcc/8.3.1-20190703/bin/arm-none-eabi-gcc-8.3.1.exe" -c -mcpu=cortex-m4 -march=armv7e-m -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -Dprintf=iprintf -DF_CPU=120000000L -DENERGIA_EK_TM4C1294XL -DENERGIA_ARCH_TIVAC -DENERGIA=23 -DARDUINO=10610 -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system/driverlib" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system/inc" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/cores/tivac" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/variants/EK-TM4C1294XL" -I"C:/Users/14169/workspace_v10/tivac_EK-TM4C1294XL_core" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/tools/arm-none-eabi-gcc/8.3.1-20190703/arm-none-eabi/include" -Os -ffunction-sections -fdata-sections -g -gdwarf-3 -gstrict-dwarf -w -Wall --param max-inline-insns-single=500 -mabi=aapcs -MMD -MP -MF"src/core/$(basename $(<F)).d_raw" -MT"$(@)" -std=gnu++11 -fno-rtti -fno-threadsafe-statics -fno-exceptions $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/new.o: C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/cores/tivac/new.cpp $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: GNU Compiler'
	"C:/Users/14169/AppData/Local/Energia15/packages/energia/tools/arm-none-eabi-gcc/8.3.1-20190703/bin/arm-none-eabi-gcc-8.3.1.exe" -c -mcpu=cortex-m4 -march=armv7e-m -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -Dprintf=iprintf -DF_CPU=120000000L -DENERGIA_EK_TM4C1294XL -DENERGIA_ARCH_TIVAC -DENERGIA=23 -DARDUINO=10610 -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system/driverlib" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system/inc" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/cores/tivac" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/variants/EK-TM4C1294XL" -I"C:/Users/14169/workspace_v10/tivac_EK-TM4C1294XL_core" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/tools/arm-none-eabi-gcc/8.3.1-20190703/arm-none-eabi/include" -Os -ffunction-sections -fdata-sections -g -gdwarf-3 -gstrict-dwarf -w -Wall --param max-inline-insns-single=500 -mabi=aapcs -MMD -MP -MF"src/core/$(basename $(<F)).d_raw" -MT"$(@)" -std=gnu++11 -fno-rtti -fno-threadsafe-statics -fno-exceptions $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/random.o: C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/cores/tivac/random.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: GNU Compiler'
	"C:/Users/14169/AppData/Local/Energia15/packages/energia/tools/arm-none-eabi-gcc/8.3.1-20190703/bin/arm-none-eabi-gcc-8.3.1.exe" -c -mcpu=cortex-m4 -march=armv7e-m -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -Dprintf=iprintf -DF_CPU=120000000L -DENERGIA_EK_TM4C1294XL -DENERGIA_ARCH_TIVAC -DENERGIA=23 -DARDUINO=10610 -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system/driverlib" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system/inc" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/cores/tivac" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/variants/EK-TM4C1294XL" -I"C:/Users/14169/workspace_v10/tivac_EK-TM4C1294XL_core" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/tools/arm-none-eabi-gcc/8.3.1-20190703/arm-none-eabi/include" -Os -ffunction-sections -fdata-sections -g -gdwarf-3 -gstrict-dwarf -w -Wall --param max-inline-insns-single=500 -mabi=aapcs -MMD -MP -MF"src/core/$(basename $(<F)).d_raw" -MT"$(@)" -std=gnu11 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/startup_gcc.o: C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/cores/tivac/startup_gcc.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: GNU Compiler'
	"C:/Users/14169/AppData/Local/Energia15/packages/energia/tools/arm-none-eabi-gcc/8.3.1-20190703/bin/arm-none-eabi-gcc-8.3.1.exe" -c -mcpu=cortex-m4 -march=armv7e-m -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -Dprintf=iprintf -DF_CPU=120000000L -DENERGIA_EK_TM4C1294XL -DENERGIA_ARCH_TIVAC -DENERGIA=23 -DARDUINO=10610 -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system/driverlib" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system/inc" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/cores/tivac" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/variants/EK-TM4C1294XL" -I"C:/Users/14169/workspace_v10/tivac_EK-TM4C1294XL_core" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/tools/arm-none-eabi-gcc/8.3.1-20190703/arm-none-eabi/include" -Os -ffunction-sections -fdata-sections -g -gdwarf-3 -gstrict-dwarf -w -Wall --param max-inline-insns-single=500 -mabi=aapcs -MMD -MP -MF"src/core/$(basename $(<F)).d_raw" -MT"$(@)" -std=gnu11 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/wiring.o: C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/cores/tivac/wiring.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: GNU Compiler'
	"C:/Users/14169/AppData/Local/Energia15/packages/energia/tools/arm-none-eabi-gcc/8.3.1-20190703/bin/arm-none-eabi-gcc-8.3.1.exe" -c -mcpu=cortex-m4 -march=armv7e-m -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -Dprintf=iprintf -DF_CPU=120000000L -DENERGIA_EK_TM4C1294XL -DENERGIA_ARCH_TIVAC -DENERGIA=23 -DARDUINO=10610 -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system/driverlib" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system/inc" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/cores/tivac" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/variants/EK-TM4C1294XL" -I"C:/Users/14169/workspace_v10/tivac_EK-TM4C1294XL_core" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/tools/arm-none-eabi-gcc/8.3.1-20190703/arm-none-eabi/include" -Os -ffunction-sections -fdata-sections -g -gdwarf-3 -gstrict-dwarf -w -Wall --param max-inline-insns-single=500 -mabi=aapcs -MMD -MP -MF"src/core/$(basename $(<F)).d_raw" -MT"$(@)" -std=gnu11 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/wiring_analog.o: C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/cores/tivac/wiring_analog.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: GNU Compiler'
	"C:/Users/14169/AppData/Local/Energia15/packages/energia/tools/arm-none-eabi-gcc/8.3.1-20190703/bin/arm-none-eabi-gcc-8.3.1.exe" -c -mcpu=cortex-m4 -march=armv7e-m -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -Dprintf=iprintf -DF_CPU=120000000L -DENERGIA_EK_TM4C1294XL -DENERGIA_ARCH_TIVAC -DENERGIA=23 -DARDUINO=10610 -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system/driverlib" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system/inc" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/cores/tivac" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/variants/EK-TM4C1294XL" -I"C:/Users/14169/workspace_v10/tivac_EK-TM4C1294XL_core" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/tools/arm-none-eabi-gcc/8.3.1-20190703/arm-none-eabi/include" -Os -ffunction-sections -fdata-sections -g -gdwarf-3 -gstrict-dwarf -w -Wall --param max-inline-insns-single=500 -mabi=aapcs -MMD -MP -MF"src/core/$(basename $(<F)).d_raw" -MT"$(@)" -std=gnu11 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/wiring_digital.o: C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/cores/tivac/wiring_digital.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: GNU Compiler'
	"C:/Users/14169/AppData/Local/Energia15/packages/energia/tools/arm-none-eabi-gcc/8.3.1-20190703/bin/arm-none-eabi-gcc-8.3.1.exe" -c -mcpu=cortex-m4 -march=armv7e-m -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -Dprintf=iprintf -DF_CPU=120000000L -DENERGIA_EK_TM4C1294XL -DENERGIA_ARCH_TIVAC -DENERGIA=23 -DARDUINO=10610 -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system/driverlib" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system/inc" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/cores/tivac" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/variants/EK-TM4C1294XL" -I"C:/Users/14169/workspace_v10/tivac_EK-TM4C1294XL_core" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/tools/arm-none-eabi-gcc/8.3.1-20190703/arm-none-eabi/include" -Os -ffunction-sections -fdata-sections -g -gdwarf-3 -gstrict-dwarf -w -Wall --param max-inline-insns-single=500 -mabi=aapcs -MMD -MP -MF"src/core/$(basename $(<F)).d_raw" -MT"$(@)" -std=gnu11 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/wiring_pulse.o: C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/cores/tivac/wiring_pulse.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: GNU Compiler'
	"C:/Users/14169/AppData/Local/Energia15/packages/energia/tools/arm-none-eabi-gcc/8.3.1-20190703/bin/arm-none-eabi-gcc-8.3.1.exe" -c -mcpu=cortex-m4 -march=armv7e-m -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -Dprintf=iprintf -DF_CPU=120000000L -DENERGIA_EK_TM4C1294XL -DENERGIA_ARCH_TIVAC -DENERGIA=23 -DARDUINO=10610 -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system/driverlib" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system/inc" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/cores/tivac" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/variants/EK-TM4C1294XL" -I"C:/Users/14169/workspace_v10/tivac_EK-TM4C1294XL_core" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/tools/arm-none-eabi-gcc/8.3.1-20190703/arm-none-eabi/include" -Os -ffunction-sections -fdata-sections -g -gdwarf-3 -gstrict-dwarf -w -Wall --param max-inline-insns-single=500 -mabi=aapcs -MMD -MP -MF"src/core/$(basename $(<F)).d_raw" -MT"$(@)" -std=gnu11 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

src/core/wiring_shift.o: C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/cores/tivac/wiring_shift.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: GNU Compiler'
	"C:/Users/14169/AppData/Local/Energia15/packages/energia/tools/arm-none-eabi-gcc/8.3.1-20190703/bin/arm-none-eabi-gcc-8.3.1.exe" -c -mcpu=cortex-m4 -march=armv7e-m -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -Dprintf=iprintf -DF_CPU=120000000L -DENERGIA_EK_TM4C1294XL -DENERGIA_ARCH_TIVAC -DENERGIA=23 -DARDUINO=10610 -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system/driverlib" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system/inc" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/system" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/cores/tivac" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/hardware/tivac/1.0.4/variants/EK-TM4C1294XL" -I"C:/Users/14169/workspace_v10/tivac_EK-TM4C1294XL_core" -I"C:/Users/14169/AppData/Local/Energia15/packages/energia/tools/arm-none-eabi-gcc/8.3.1-20190703/arm-none-eabi/include" -Os -ffunction-sections -fdata-sections -g -gdwarf-3 -gstrict-dwarf -w -Wall --param max-inline-insns-single=500 -mabi=aapcs -MMD -MP -MF"src/core/$(basename $(<F)).d_raw" -MT"$(@)" -std=gnu11 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '


