################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../FREERTOS_TCP_SOURCE/FreeRTOS_ARP.c \
../FREERTOS_TCP_SOURCE/FreeRTOS_DHCP.c \
../FREERTOS_TCP_SOURCE/FreeRTOS_DNS.c \
../FREERTOS_TCP_SOURCE/FreeRTOS_DNS_Cache.c \
../FREERTOS_TCP_SOURCE/FreeRTOS_DNS_Callback.c \
../FREERTOS_TCP_SOURCE/FreeRTOS_DNS_Networking.c \
../FREERTOS_TCP_SOURCE/FreeRTOS_DNS_Parser.c \
../FREERTOS_TCP_SOURCE/FreeRTOS_ICMP.c \
../FREERTOS_TCP_SOURCE/FreeRTOS_IP.c \
../FREERTOS_TCP_SOURCE/FreeRTOS_IP_Timers.c \
../FREERTOS_TCP_SOURCE/FreeRTOS_IP_Utils.c \
../FREERTOS_TCP_SOURCE/FreeRTOS_Sockets.c \
../FREERTOS_TCP_SOURCE/FreeRTOS_Stream_Buffer.c \
../FREERTOS_TCP_SOURCE/FreeRTOS_TCP_IP.c \
../FREERTOS_TCP_SOURCE/FreeRTOS_TCP_Reception.c \
../FREERTOS_TCP_SOURCE/FreeRTOS_TCP_State_Handling.c \
../FREERTOS_TCP_SOURCE/FreeRTOS_TCP_Transmission.c \
../FREERTOS_TCP_SOURCE/FreeRTOS_TCP_Utils.c \
../FREERTOS_TCP_SOURCE/FreeRTOS_TCP_WIN.c \
../FREERTOS_TCP_SOURCE/FreeRTOS_Tiny_TCP.c \
../FREERTOS_TCP_SOURCE/FreeRTOS_UDP_IP.c 

C_DEPS += \
./FREERTOS_TCP_SOURCE/FreeRTOS_ARP.d \
./FREERTOS_TCP_SOURCE/FreeRTOS_DHCP.d \
./FREERTOS_TCP_SOURCE/FreeRTOS_DNS.d \
./FREERTOS_TCP_SOURCE/FreeRTOS_DNS_Cache.d \
./FREERTOS_TCP_SOURCE/FreeRTOS_DNS_Callback.d \
./FREERTOS_TCP_SOURCE/FreeRTOS_DNS_Networking.d \
./FREERTOS_TCP_SOURCE/FreeRTOS_DNS_Parser.d \
./FREERTOS_TCP_SOURCE/FreeRTOS_ICMP.d \
./FREERTOS_TCP_SOURCE/FreeRTOS_IP.d \
./FREERTOS_TCP_SOURCE/FreeRTOS_IP_Timers.d \
./FREERTOS_TCP_SOURCE/FreeRTOS_IP_Utils.d \
./FREERTOS_TCP_SOURCE/FreeRTOS_Sockets.d \
./FREERTOS_TCP_SOURCE/FreeRTOS_Stream_Buffer.d \
./FREERTOS_TCP_SOURCE/FreeRTOS_TCP_IP.d \
./FREERTOS_TCP_SOURCE/FreeRTOS_TCP_Reception.d \
./FREERTOS_TCP_SOURCE/FreeRTOS_TCP_State_Handling.d \
./FREERTOS_TCP_SOURCE/FreeRTOS_TCP_Transmission.d \
./FREERTOS_TCP_SOURCE/FreeRTOS_TCP_Utils.d \
./FREERTOS_TCP_SOURCE/FreeRTOS_TCP_WIN.d \
./FREERTOS_TCP_SOURCE/FreeRTOS_Tiny_TCP.d \
./FREERTOS_TCP_SOURCE/FreeRTOS_UDP_IP.d 

OBJS += \
./FREERTOS_TCP_SOURCE/FreeRTOS_ARP.obj \
./FREERTOS_TCP_SOURCE/FreeRTOS_DHCP.obj \
./FREERTOS_TCP_SOURCE/FreeRTOS_DNS.obj \
./FREERTOS_TCP_SOURCE/FreeRTOS_DNS_Cache.obj \
./FREERTOS_TCP_SOURCE/FreeRTOS_DNS_Callback.obj \
./FREERTOS_TCP_SOURCE/FreeRTOS_DNS_Networking.obj \
./FREERTOS_TCP_SOURCE/FreeRTOS_DNS_Parser.obj \
./FREERTOS_TCP_SOURCE/FreeRTOS_ICMP.obj \
./FREERTOS_TCP_SOURCE/FreeRTOS_IP.obj \
./FREERTOS_TCP_SOURCE/FreeRTOS_IP_Timers.obj \
./FREERTOS_TCP_SOURCE/FreeRTOS_IP_Utils.obj \
./FREERTOS_TCP_SOURCE/FreeRTOS_Sockets.obj \
./FREERTOS_TCP_SOURCE/FreeRTOS_Stream_Buffer.obj \
./FREERTOS_TCP_SOURCE/FreeRTOS_TCP_IP.obj \
./FREERTOS_TCP_SOURCE/FreeRTOS_TCP_Reception.obj \
./FREERTOS_TCP_SOURCE/FreeRTOS_TCP_State_Handling.obj \
./FREERTOS_TCP_SOURCE/FreeRTOS_TCP_Transmission.obj \
./FREERTOS_TCP_SOURCE/FreeRTOS_TCP_Utils.obj \
./FREERTOS_TCP_SOURCE/FreeRTOS_TCP_WIN.obj \
./FREERTOS_TCP_SOURCE/FreeRTOS_Tiny_TCP.obj \
./FREERTOS_TCP_SOURCE/FreeRTOS_UDP_IP.obj 

OBJS__QUOTED += \
"FREERTOS_TCP_SOURCE\FreeRTOS_ARP.obj" \
"FREERTOS_TCP_SOURCE\FreeRTOS_DHCP.obj" \
"FREERTOS_TCP_SOURCE\FreeRTOS_DNS.obj" \
"FREERTOS_TCP_SOURCE\FreeRTOS_DNS_Cache.obj" \
"FREERTOS_TCP_SOURCE\FreeRTOS_DNS_Callback.obj" \
"FREERTOS_TCP_SOURCE\FreeRTOS_DNS_Networking.obj" \
"FREERTOS_TCP_SOURCE\FreeRTOS_DNS_Parser.obj" \
"FREERTOS_TCP_SOURCE\FreeRTOS_ICMP.obj" \
"FREERTOS_TCP_SOURCE\FreeRTOS_IP.obj" \
"FREERTOS_TCP_SOURCE\FreeRTOS_IP_Timers.obj" \
"FREERTOS_TCP_SOURCE\FreeRTOS_IP_Utils.obj" \
"FREERTOS_TCP_SOURCE\FreeRTOS_Sockets.obj" \
"FREERTOS_TCP_SOURCE\FreeRTOS_Stream_Buffer.obj" \
"FREERTOS_TCP_SOURCE\FreeRTOS_TCP_IP.obj" \
"FREERTOS_TCP_SOURCE\FreeRTOS_TCP_Reception.obj" \
"FREERTOS_TCP_SOURCE\FreeRTOS_TCP_State_Handling.obj" \
"FREERTOS_TCP_SOURCE\FreeRTOS_TCP_Transmission.obj" \
"FREERTOS_TCP_SOURCE\FreeRTOS_TCP_Utils.obj" \
"FREERTOS_TCP_SOURCE\FreeRTOS_TCP_WIN.obj" \
"FREERTOS_TCP_SOURCE\FreeRTOS_Tiny_TCP.obj" \
"FREERTOS_TCP_SOURCE\FreeRTOS_UDP_IP.obj" 

C_DEPS__QUOTED += \
"FREERTOS_TCP_SOURCE\FreeRTOS_ARP.d" \
"FREERTOS_TCP_SOURCE\FreeRTOS_DHCP.d" \
"FREERTOS_TCP_SOURCE\FreeRTOS_DNS.d" \
"FREERTOS_TCP_SOURCE\FreeRTOS_DNS_Cache.d" \
"FREERTOS_TCP_SOURCE\FreeRTOS_DNS_Callback.d" \
"FREERTOS_TCP_SOURCE\FreeRTOS_DNS_Networking.d" \
"FREERTOS_TCP_SOURCE\FreeRTOS_DNS_Parser.d" \
"FREERTOS_TCP_SOURCE\FreeRTOS_ICMP.d" \
"FREERTOS_TCP_SOURCE\FreeRTOS_IP.d" \
"FREERTOS_TCP_SOURCE\FreeRTOS_IP_Timers.d" \
"FREERTOS_TCP_SOURCE\FreeRTOS_IP_Utils.d" \
"FREERTOS_TCP_SOURCE\FreeRTOS_Sockets.d" \
"FREERTOS_TCP_SOURCE\FreeRTOS_Stream_Buffer.d" \
"FREERTOS_TCP_SOURCE\FreeRTOS_TCP_IP.d" \
"FREERTOS_TCP_SOURCE\FreeRTOS_TCP_Reception.d" \
"FREERTOS_TCP_SOURCE\FreeRTOS_TCP_State_Handling.d" \
"FREERTOS_TCP_SOURCE\FreeRTOS_TCP_Transmission.d" \
"FREERTOS_TCP_SOURCE\FreeRTOS_TCP_Utils.d" \
"FREERTOS_TCP_SOURCE\FreeRTOS_TCP_WIN.d" \
"FREERTOS_TCP_SOURCE\FreeRTOS_Tiny_TCP.d" \
"FREERTOS_TCP_SOURCE\FreeRTOS_UDP_IP.d" 

C_SRCS__QUOTED += \
"../FREERTOS_TCP_SOURCE/FreeRTOS_ARP.c" \
"../FREERTOS_TCP_SOURCE/FreeRTOS_DHCP.c" \
"../FREERTOS_TCP_SOURCE/FreeRTOS_DNS.c" \
"../FREERTOS_TCP_SOURCE/FreeRTOS_DNS_Cache.c" \
"../FREERTOS_TCP_SOURCE/FreeRTOS_DNS_Callback.c" \
"../FREERTOS_TCP_SOURCE/FreeRTOS_DNS_Networking.c" \
"../FREERTOS_TCP_SOURCE/FreeRTOS_DNS_Parser.c" \
"../FREERTOS_TCP_SOURCE/FreeRTOS_ICMP.c" \
"../FREERTOS_TCP_SOURCE/FreeRTOS_IP.c" \
"../FREERTOS_TCP_SOURCE/FreeRTOS_IP_Timers.c" \
"../FREERTOS_TCP_SOURCE/FreeRTOS_IP_Utils.c" \
"../FREERTOS_TCP_SOURCE/FreeRTOS_Sockets.c" \
"../FREERTOS_TCP_SOURCE/FreeRTOS_Stream_Buffer.c" \
"../FREERTOS_TCP_SOURCE/FreeRTOS_TCP_IP.c" \
"../FREERTOS_TCP_SOURCE/FreeRTOS_TCP_Reception.c" \
"../FREERTOS_TCP_SOURCE/FreeRTOS_TCP_State_Handling.c" \
"../FREERTOS_TCP_SOURCE/FreeRTOS_TCP_Transmission.c" \
"../FREERTOS_TCP_SOURCE/FreeRTOS_TCP_Utils.c" \
"../FREERTOS_TCP_SOURCE/FreeRTOS_TCP_WIN.c" \
"../FREERTOS_TCP_SOURCE/FreeRTOS_Tiny_TCP.c" \
"../FREERTOS_TCP_SOURCE/FreeRTOS_UDP_IP.c" 


