/*
Generated by LwipMibCompiler
*/

#ifndef UPS_PRIVATE_MIB_H
#define UPS_PRIVATE_MIB_H

#include "lwip/apps/snmp_opts.h"
#if LWIP_SNMP

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "lwip/apps/snmp.h"
#include "lwip/apps/snmp_core.h"
#include "lwip/apps/snmp_scalar.h"
#include "lwip/apps/snmp_table.h"

s16_t upsinput_treenode_get_value(struct snmp_node_instance *instance, void *value);
snmp_err_t upsintable_get_instance(const u32_t *column, const u32_t *row_oid, u8_t row_oid_len, struct snmp_node_instance *cell_instance);
snmp_err_t upsintable_get_next_instance(const u32_t *column, struct snmp_obj_id *row_oid, struct snmp_node_instance *cell_instance);
s16_t upsintable_get_value(struct snmp_node_instance *cell_instance, void *value);


s16_t upsoutput_treenode_get_value(struct snmp_node_instance *instance, void *value);
snmp_err_t upsouttable_get_instance(const u32_t *column, const u32_t *row_oid, u8_t row_oid_len, struct snmp_node_instance *cell_instance);
snmp_err_t upsouttable_get_next_instance(const u32_t *column, struct snmp_obj_id *row_oid, struct snmp_node_instance *cell_instance);
s16_t upsouttable_get_value(struct snmp_node_instance *cell_instance, void *value);


s16_t upsbypass_treenode_get_value(struct snmp_node_instance *instance, void *value);
snmp_err_t upsbytable_get_instance(const u32_t *column, const u32_t *row_oid, u8_t row_oid_len, struct snmp_node_instance *cell_instance);
snmp_err_t upsbytable_get_next_instance(const u32_t *column, struct snmp_obj_id *row_oid, struct snmp_node_instance *cell_instance);
s16_t upsbytable_get_value(struct snmp_node_instance *cell_instance, void *value);

s16_t upsident_scalars_get_value(const struct snmp_scalar_array_node_def *node, void *value);
snmp_err_t upsident_scalars_set_test(const struct snmp_scalar_array_node_def *node, u16_t len, void *value);
snmp_err_t upsident_scalars_set_value(const struct snmp_scalar_array_node_def *node, u16_t len, void *value);

s16_t upsrating_scalars_get_value(const struct snmp_scalar_array_node_def *node, void *value);

s16_t upsbattery_scalars_get_value(const struct snmp_scalar_array_node_def *node, void *value);


s16_t upstest_scalars_get_value(const struct snmp_scalar_array_node_def *node, void *value);
snmp_err_t upstest_scalars_set_test(const struct snmp_scalar_array_node_def *node, u16_t len, void *value);
snmp_err_t upstest_scalars_set_value(const struct snmp_scalar_array_node_def *node, u16_t len, void *value);


s16_t upscontrol_scalars_get_value(const struct snmp_scalar_array_node_def *node, void *value);
snmp_err_t upscontrol_scalars_set_test(const struct snmp_scalar_array_node_def *node, u16_t len, void *value);
snmp_err_t upscontrol_scalars_set_value(const struct snmp_scalar_array_node_def *node, u16_t len, void *value);


s16_t agentconfig_scalars_get_value(const struct snmp_scalar_array_node_def *node, void *value);
snmp_err_t agentconfig_scalars_set_test(const struct snmp_scalar_array_node_def *node, u16_t len, void *value);
snmp_err_t agentconfig_scalars_set_value(const struct snmp_scalar_array_node_def *node, u16_t len, void *value);

s16_t commconfig_scalars_get_value(const struct snmp_scalar_array_node_def *node, void *value);
snmp_err_t commconfig_scalars_set_test(const struct snmp_scalar_array_node_def *node, u16_t len, void *value);
snmp_err_t commconfig_scalars_set_value(const struct snmp_scalar_array_node_def *node, u16_t len, void *value);


s16_t upsconfig_scalars_get_value(const struct snmp_scalar_array_node_def *node, void *value);
snmp_err_t upsconfig_scalars_set_test(const struct snmp_scalar_array_node_def *node, u16_t len, void *value);
snmp_err_t upsconfig_scalars_set_value(const struct snmp_scalar_array_node_def *node, u16_t len, void *value);


s16_t extend_scalars_get_value(const struct snmp_scalar_array_node_def *node, void *value);

extern const struct snmp_mib companymib;

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* LWIP_SNMP */
#endif /* UPS_PRIVATE_MIB_H */
